name = "kaia-checklist"
main = ".open-next/worker.js"
compatibility_date = "2026-03-24"
compatibility_flags = ["nodejs_compat"]
[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "kaia-checklist"
database_id = "00f840dd-4d81-42db-9576-63f72757762e"
